import type { Metadata } from "next"

import "./globals.css"

import { Poppins, Volkhov } from "next/font/google"

const poppins = Poppins({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
})

const volkhov = Volkhov({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-volkhov",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} min-h-screen antialiased`}>
        {children}
      </body>
    </html>
  )
}
